### ISSUE TITLE
How to use Motionblur. H5 ?

### ISSUE THREAD

**Issue by YYYYWD** [Sibozhu/MotionBlur-detection-by-using-CNN#1]
I'm very interested in this project.Can you do me a few favors?
Motionblur. H5 is the trained weight file. Where is the file to call it?
Are we required to do it ourselves?

**Comment by YYYYWD** [comment]
I think i know your means. But this paper is used for removing blur. Your code only detect where is blurred？

**Comment by Sibozhu** [comment]
I'm sorry the original goal was to remove the blur, however, something we didn't expect happened and the project is no longer under development. I'm giving the weight to the public is also hoping people could continue doing what I left or maybe one day I'll come back for this. 
Yes, right now what we have done is only detecting the blurry part of the image.
